/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { SurveyService } from "../survey.service";
import { SurveyCreateInput } from "./SurveyCreateInput";
import { Survey } from "./Survey";
import { SurveyFindManyArgs } from "./SurveyFindManyArgs";
import { SurveyWhereUniqueInput } from "./SurveyWhereUniqueInput";
import { SurveyUpdateInput } from "./SurveyUpdateInput";
import { QuestionFindManyArgs } from "../../question/base/QuestionFindManyArgs";
import { Question } from "../../question/base/Question";
import { QuestionWhereUniqueInput } from "../../question/base/QuestionWhereUniqueInput";

export class SurveyControllerBase {
  constructor(protected readonly service: SurveyService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Survey })
  async createSurvey(@common.Body() data: SurveyCreateInput): Promise<Survey> {
    return await this.service.createSurvey({
      data: data,
      select: {
        createdAt: true,
        description: true,
        id: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Survey] })
  @ApiNestedQuery(SurveyFindManyArgs)
  async surveys(@common.Req() request: Request): Promise<Survey[]> {
    const args = plainToClass(SurveyFindManyArgs, request.query);
    return this.service.surveys({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Survey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async survey(
    @common.Param() params: SurveyWhereUniqueInput
  ): Promise<Survey | null> {
    const result = await this.service.survey({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        status: true,
        title: true,
        updatedAt: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Survey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateSurvey(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() data: SurveyUpdateInput
  ): Promise<Survey | null> {
    try {
      return await this.service.updateSurvey({
        where: params,
        data: data,
        select: {
          createdAt: true,
          description: true,
          id: true,
          status: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Survey })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteSurvey(
    @common.Param() params: SurveyWhereUniqueInput
  ): Promise<Survey | null> {
    try {
      return await this.service.deleteSurvey({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          status: true,
          title: true,
          updatedAt: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/questions")
  @ApiNestedQuery(QuestionFindManyArgs)
  async findQuestions(
    @common.Req() request: Request,
    @common.Param() params: SurveyWhereUniqueInput
  ): Promise<Question[]> {
    const query = plainToClass(QuestionFindManyArgs, request.query);
    const results = await this.service.findQuestions(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,

        survey: {
          select: {
            id: true,
          },
        },

        text: true,
        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/questions")
  async connectQuestions(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: QuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        connect: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/questions")
  async updateQuestions(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: QuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        set: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/questions")
  async disconnectQuestions(
    @common.Param() params: SurveyWhereUniqueInput,
    @common.Body() body: QuestionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      questions: {
        disconnect: body,
      },
    };
    await this.service.updateSurvey({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Post("/surveys")
  @swagger.ApiOkResponse({
    type: Survey,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async CreateSurvey(
    @common.Body()
    body: SurveyUpdateInput
  ): Promise<Survey> {
    return this.service.CreateSurvey(body);
  }

  @common.Delete("/surveys/:id")
  @swagger.ApiOkResponse({
    type: Survey,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async DeleteSurvey(
    @common.Body()
    body: SurveyUpdateInput
  ): Promise<Survey> {
    return this.service.DeleteSurvey(body);
  }

  @common.Get("/surveys")
  @swagger.ApiOkResponse({
    type: Survey,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetAllSurveys(
    @common.Body()
    body: SurveyUpdateInput
  ): Promise<Survey[]> {
    return this.service.GetAllSurveys(body);
  }

  @common.Get("/surveys/:id")
  @swagger.ApiOkResponse({
    type: Survey,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async GetSurveyById(
    @common.Body()
    body: SurveyUpdateInput
  ): Promise<Survey> {
    return this.service.GetSurveyById(body);
  }

  @common.Put("/surveys/:id")
  @swagger.ApiOkResponse({
    type: Survey,
  })
  @swagger.ApiNotFoundResponse({
    type: errors.NotFoundException,
  })
  @swagger.ApiForbiddenResponse({
    type: errors.ForbiddenException,
  })
  async UpdateSurvey(
    @common.Body()
    body: SurveyUpdateInput
  ): Promise<Survey> {
    return this.service.UpdateSurvey(body);
  }
}
